version: '2.3'

services:
  rstudio:
    image: "ecohealthalliance/rockergpu"
    environment:
#      -  DISABLE_AUTH=true
      -  PASSWORD=prospero
      -  ROOT=true
    ports:
#      - "22022:22"
      - "8787:8787"
#    volumes:
#      - ".:/home/rstudio"
    hostname: rockergpu
    runtime: nvidia
