
version: '3.1'

services:
  rstudio:
    image: "ecohealthalliance/rockergpu"
    environment:
      -  DISABLE_AUTH=true
    ports:
      - "22022:22"
      - "8787:8787"
    volumes:
      - ".:/home/rstudio"
    hostname: rockergpu
